services:
  bedbusters_app:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npx prisma generate && npm run ${START_COMMAND:-dev}"
    depends_on:
      - bedbusters_db

  bedbusters_db:
    image: postgres:17.3
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest  # Use the latest version of pgAdmin
    profiles:
      - dev  # This service will only run if the profile "dev" is enabled
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PWD}
    ports:
      - "8080:80"
    depends_on:
      - bedbusters_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
