version: "3.8"
name: bedbusters

services:
  bedbusters_app:
    image: node:18-alpine
    profiles:
      - prod
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - API_KEY=${API_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - SERVER_IP=${SERVER_IP}
      - PORT=${PORT}
      - PUBLIC_URL=${PUBLIC_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - RIB=${RIB}
      - TJW_SECRET_KEY=${TJW_SECRET_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_OIDC_ISSUER=${AUTH_OIDC_ISSUER}
      - AUTH_OIDC_CLIENT_ID=${AUTH_OIDC_CLIENT_ID}
      - AUTH_OIDC_CLIENT_SECRET=${AUTH_OIDC_CLIENT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    command: 'sh -c "npm install && npx prisma generate && npm run build && npm start"'
    depends_on:
      - bedbusters_db

  bedbusters_db:
    image: postgres:17.3
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    profiles:
      - dev  # Ce service ne s'exécute que si le profil "dev" est activé
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PWD}
    ports:
      - "8080:80"
    depends_on:
      - bedbusters_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Volume pour pgAdmin

volumes:
  postgres_data: {}  # Définition du volume pour la base de données
  pgadmin_data: {}   # Définition du volume pour pgAdmin
